"""Deterministic Obsidian-readable dashboard and Session Receipt renderers."""

from __future__ import annotations

import html
import json
import re
from typing import Any

from .grounding import GroundingTimeline, reduce_grounding_timeline

GENERATED_WARNING = (
    "> [!warning] Generated by Dunk. Do not edit this file; edit `profile.yaml` instead.\n"
)
SYLLABUS_GENERATED_WARNING = (
    "> [!warning] Generated from canonical `profile.yaml` and `events.jsonl`. "
    "Use the Dunk store commands instead of editing this receipt.\n"
)


def markdown_text(value: Any) -> str:
    """Escape untrusted inline Markdown, table cells, and block marker syntax."""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = html.escape(text, quote=False).replace("\\", "\\\\").replace("|", "\\|")
    for marker in ("`", "*", "[", "]"):
        text = text.replace(marker, f"\\{marker}")
    return text.replace("\n", "<br>")


def _outcome(event: dict[str, Any]) -> str:
    result = event["outcome"]
    if "score" in event:
        result += f" ({event['score']}/{event['max_score']})"
    return markdown_text(result)


def _retrieval_marker(evidence_mode: str) -> str:
    return "" if evidence_mode == "independent" else " (supported)"


def _normalized_text(value: Any) -> str:
    if isinstance(value, str):
        return markdown_text(value)
    return markdown_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    )


def _page_text_fence(text: str) -> str:
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    return "`" * max(4, longest + 1)


def _citation_text(citation: dict[str, Any]) -> str:
    unit = citation.get("unit_id") or f"page:{citation.get('page_number')}"
    return (
        f"{markdown_text(unit)}, chars {citation['start_char']}–{citation['end_char']}: "
        f"“{markdown_text(citation['quote'])}”"
    )


def _render_assertion(lines: list[str], assertion: dict[str, Any]) -> None:
    normalized = _normalized_text(assertion["normalized_value"])
    lines.append(
        f"- `{markdown_text(assertion['assertion_id'])}` — "
        f"`{markdown_text(assertion['field'])}` = {normalized} "
        f"(`{markdown_text(assertion['status'])}`)"
    )
    if assertion.get("origin") == "learner_correction":
        lines.append(
            f"  - Learner correction of `{markdown_text(assertion['source_assertion_id'])}`; "
            f"document value: {_normalized_text(assertion['document_value'])}; "
            f"rationale: {markdown_text(assertion['rationale'])}"
        )
    for citation in assertion.get("citations", []):
        lines.append(f"  - {_citation_text(citation)}")
    for citation in assertion.get("document_context", []):
        lines.append(f"  - Preserved document context (not support for correction): {_citation_text(citation)}")
    note = assertion.get("note") or assertion.get("document_note")
    if note:
        lines.append(f"  - Note: {markdown_text(note)}")


def render_syllabus_receipt(timeline: GroundingTimeline, source: dict[str, Any]) -> bytes:
    """Render one media-neutral authoritative or supplemental source lifecycle."""
    views = [view for view in timeline.approval_views.values() if view["source"]["event_id"] == source["event_id"]]
    latest = views[-1] if views else None
    current = timeline.current_view()
    active = bool(current and current["source"]["event_id"] == source["event_id"])
    role_label = "Authoritative" if source["role"] == "authoritative" else "Non-Authoritative Supplement"
    if source["phase"] == "prepared":
        phase = "Proposal Required"
    elif source["phase"] == "proposed":
        phase = "Decision Required"
    elif active:
        phase = "Approved"
    elif source["role"] == "supplement":
        phase = "Decided — Display Only"
    else:
        phase = "Historically Approved — Superseded"
    lines = [f"# Syllabus Receipt — {role_label} — {phase}", "", SYLLABUS_GENERATED_WARNING.rstrip("\n"), "",
             f"- **Role:** `{source['role']}`", f"- **Storage:** `{source['storage']}`",
             f"- **Source version:** `{markdown_text(source['source_version_id'])}`",
             f"- **Filename:** {markdown_text(source['display_name'])}", f"- **Media type:** `{markdown_text(source['media_type'])}`",
             f"- **Source SHA-256:** `{source['sha256']}`", f"- **Prepared SHA-256:** `{source.get('prepared_document_sha256') or 'legacy-inline-only'}`",
             f"- **Recorded:** {markdown_text(source['occurred_at'])}"]
    if source["role"] == "supplement":
        lines.extend(["", "> [!important] This supplement is permanently non-authoritative and cannot drive active grounding, planning topics, or eligible learning citations."])
    proposals = (latest or {}).get("proposals") or timeline.proposals_by_source_event.get(source["event_id"], {}).get("proposals", [])
    rendered = latest["effective_assertions"] if latest else [_proposal_preview(item) for item in proposals]
    lines.extend(["", "## Assertions", ""])
    if rendered:
        for assertion in rendered:
            _render_assertion(lines, assertion)
    else:
        lines.append("No proposal set has been recorded.")
    unresolved = latest["unresolved_assertions"] if latest else [_proposal_preview(item) for item in proposals if item["status"] != "specified"]
    lines.extend(["", "## Deferred / Ambiguous / Unknown", ""])
    if unresolved:
        for assertion in unresolved:
            _render_assertion(lines, assertion)
    else:
        lines.append("None.")
    rejected = latest.get("rejected_assertions", []) if latest else []
    lines.extend(["", "## Rejected", ""])
    if rejected:
        for assertion in rejected:
            _render_assertion(lines, assertion)
    else:
        lines.append("None.")
    lines.extend(["", "## Decision History", ""])
    if views:
        for view in views:
            decision = view["decision"]
            lines.extend([f"- `{decision['event_id']}` at {markdown_text(decision['occurred_at'])} — `{view['reference_field']}`"])
            if decision["kind"] == "syllabus_decision_recorded":
                lines.extend([
                    f"  - Accepted: {', '.join(decision['accepted_proposal_ids']) or 'none'}",
                    f"  - Deferred: {', '.join(decision['deferred_proposal_ids']) or 'none'}",
                    f"  - Rejected: {', '.join(decision['rejected_proposal_ids']) or 'none'}",
                    f"  - Corrected: {', '.join(item['target_proposal_id'] for item in decision['corrections']) or 'none'}",
                ])
            else:
                lines.extend([
                    f"  - Accepted: {', '.join(decision['accepted_assertion_ids']) or 'none'}",
                    f"  - Deferred: {', '.join(decision['deferred_assertion_ids']) or 'none'}",
                    f"  - Corrected: {', '.join(item['target_assertion_id'] for item in decision['corrections']) or 'none'}",
                ])
    else:
        lines.append("No learner decision has been recorded.")
    lines.extend(["", "## Canonical Prepared Text", ""])
    for unit in source["document"]["units"]:
        fence = _page_text_fence(unit["text"])
        lines.extend([f"### {markdown_text(unit.get('label') or unit['unit_id'])}", "", f"{fence}text", unit["text"], fence, ""])
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def _proposal_preview(proposal: dict[str, Any]) -> dict[str, Any]:
    return {"assertion_id": proposal["proposal_id"], "source_assertion_id": proposal["proposal_id"],
            "field": proposal["predicate"], "normalized_value": proposal["value"], "status": proposal["status"],
            "origin": "document", "citations": proposal["locators"]}


def render_all_syllabus_receipts(
    events: list[dict[str, Any]], timeline: GroundingTimeline | None = None
) -> dict[str, bytes]:
    """Render every source-version receipt after validating the shared timeline."""
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    return {
        f"syllabus/{version_id}.md": render_syllabus_receipt(
            timeline, timeline.sources_by_version[version_id]
        )
        for version_id in timeline.source_order + timeline.supplement_order
    }


def _dashboard_grounding_lines(grounding: dict[str, Any]) -> list[str]:
    lines = ["", "## Course Grounding", ""]
    status = grounding["status"]
    lines.append(f"- **Status:** `{markdown_text(status)}`")
    active = grounding["active_source"]
    if active is None:
        if status == "ungrounded":
            lines.append(
                "- **Source:** unknown; legacy planning topics are ungrounded and non-citable"
            )
        else:
            lines.append("- **Source:** no approved source is active")
    else:
        approval = grounding["active_approval"]
        lines.extend(
            [
                f"- **Active source:** {markdown_text(active['filename'])}",
                f"- **Version:** `{markdown_text(active['source_version_id'])}`",
                f"- **SHA-256:** `{active['sha256']}`",
                f"- **Decision/approval:** `{markdown_text(approval['event_id'])}`",
                f"- **Unresolved/deferred:** {len(grounding['unresolved_assertions'])}",
                f"- **Receipt:** [[{markdown_text(active['receipt'])}|Syllabus Intake Receipt]]",
            ]
        )
    if grounding["pending_sources"]:
        label = "Pending update" if active else "Decision required"
        for pending in grounding["pending_sources"]:
            lines.append(
                f"- **{label}:** {markdown_text(pending['filename'])} "
                f"(`{markdown_text(pending['source_version_id'])}`) — "
                f"[[{markdown_text(pending['receipt'])}|review intake receipt]]"
            )
    for supplement in grounding.get("supplements", []):
        lines.append(f"- **Non-authoritative supplement:** {markdown_text(supplement['filename'])} (`{markdown_text(supplement['phase'])}`) — [[{markdown_text(supplement['receipt'])}|view supplement]]")
    return lines


def render_dashboard(state: dict[str, Any]) -> bytes:
    """Render the domain dashboard as Obsidian-readable Markdown."""
    lines = [
        "# Dunk Learning Dashboard",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(state['domain'])}",
        f"- **Goal:** {markdown_text(state['goal'])}",
        f"- **Stage:** `{markdown_text(state['stage'])}`",
        f"- **Revision:** {state['revision']}",
        f"- **Generation:** {state['generation']}",
        f"- **Next review:** {markdown_text(state['next_review_date'] or 'not scheduled')}",
    ]
    lines.extend(_dashboard_grounding_lines(state["grounding"]))
    lines.extend(
        [
            "",
            "## Evidence",
            "",
            "| Subject | Status | Latest independent | Latest supported | Retrieval | Transfer |",
            "|---|---|---|---|---|---|",
        ]
    )
    if state["subjects"]:
        for subject in state["subjects"]:
            independent = subject["independent"]
            supported = subject["supported"]
            independent_text = (
                f"{independent['outcome']} / {independent['operation']}"
                if independent
                else "not measured"
            )
            supported_text = (
                f"{supported['outcome']} / {supported['operation']}" if supported else "none"
            )
            retrieval = subject["retrieval"]
            if retrieval["status"] == "measured":
                latest_retrieval = retrieval["latest"]
                retrieval_text = (
                    f"{latest_retrieval['outcome']} after {latest_retrieval['delay_days']} day(s)"
                    f"{_retrieval_marker(latest_retrieval['evidence_mode'])}"
                )
            else:
                retrieval_text = "not measured"
            transfer = subject["transfer"]
            transfer_text = (
                f"{transfer['count']} novel task(s)" if transfer["count"] else "not measured"
            )
            lines.append(
                "| "
                + " | ".join(
                    markdown_text(value)
                    for value in (
                        subject["label"],
                        subject["status"],
                        independent_text,
                        supported_text,
                        retrieval_text,
                        transfer_text,
                    )
                )
                + " |"
            )
    else:
        lines.append(
            "| _No structured assessment evidence yet_ | insufficient-evidence | — | — | — | — |"
        )

    calibration = state["calibration"]
    lines.extend(["", "## Calibration", ""])
    if calibration["status"] == "measured":
        lines.extend(
            [
                f"- Paired predictions: {calibration['count']}",
                f"- Mean confidence: {calibration['mean_confidence']:.3f}",
                f"- Mean normalized score: {calibration['mean_normalized_score']:.3f}",
                f"- Mean confidence minus score: {calibration['mean_gap']:.3f}",
            ]
        )
    else:
        lines.append(
            "Calibration not measured (requires confidence recorded before a scored outcome)."
        )

    lines.extend(["", "## Current Model", ""])
    if state["current_model"]:
        model = state["current_model"]
        lines.extend(
            [
                f"- **Decision:** `{markdown_text(model['decision'])}`",
                f"- **Model:** {markdown_text(model['model'])}",
                f"- **Revision rationale:** {markdown_text(model['rationale'])}",
            ]
        )
    else:
        lines.append("No structured model revision recorded.")

    lines.extend(["", "## Completed Sessions", ""])
    if state["completed_sessions"]:
        for session in state["completed_sessions"]:
            lines.append(
                f"- [[{markdown_text(session['receipt'])}|{markdown_text(session['session_id'])}]]"
                f" — {markdown_text(session['completed_at'])}"
            )
    else:
        lines.append("No completed sessions yet.")

    lines.extend(["", "## Imported Legacy Claims", ""])
    if state["legacy_imports"]:
        lines.append(
            "Legacy claims are unverified prior context only and are never counted "
            "as evidence, mastery, retrieval, or calibration."
        )
        for item in state["legacy_imports"]:
            claims = item["claims"]
            counts = ", ".join(
                f"{key}: {len(value)}"
                for key, value in sorted(claims.items())
                if isinstance(value, list)
            )
            lines.append(
                f"- `{item['source_sha256'][:12]}` — {markdown_text(counts or 'snapshot imported')}"
            )
    else:
        lines.append("No legacy snapshot imported.")

    if state["next_action"]:
        lines.extend(["", "## Next Action", "", markdown_text(state["next_action"])])
    return ("\n".join(lines) + "\n").encode("utf-8")


def _session_events(
    events: list[dict[str, Any]], completion: dict[str, Any]
) -> list[dict[str, Any]]:
    wanted = set(completion["evidence_event_ids"])
    return [event for event in events if event["event_id"] in wanted]


def render_receipt(
    profile: dict[str, Any],
    events: list[dict[str, Any]],
    completion: dict[str, Any],
    timeline: GroundingTimeline | None = None,
) -> bytes:
    """Render one Session Receipt from a completion event and its cited evidence."""
    session_events = _session_events(events, completion)
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    independent = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "independent"
    ]
    supported = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "supported"
    ]
    predictions = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["operation"] == "predict"
    ]
    revisions = [event for event in session_events if event["kind"] == "model_revision"]
    retrievals = [
        event
        for event in session_events
        if event["kind"] == "assessment"
        and event.get("retrieval", {}).get("observed_delay_days", 0) > 0
    ]
    calibrated = [event for event in session_events if "confidence_before" in event]

    lines = [
        f"# Session Receipt — {markdown_text(completion['session_id'])}",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(profile['domain'])}",
        f"- **Completed:** {markdown_text(completion['occurred_at'])}",
        "",
        "## Independent Evidence",
        "",
    ]
    if independent:
        lines.extend(["| Subject | Operation | Outcome | Novelty |", "|---|---|---|---|"])
        for event in independent:
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(event["novelty"]),
                    )
                )
                + " |"
            )
    else:
        lines.append("No independent assessment evidence was recorded in this session.")

    lines.extend(["", "## Supported Performance", ""])
    if supported:
        lines.extend(["| Subject | Operation | Outcome | Assistance |", "|---|---|---|---|"])
        for event in supported:
            assistance = event["assistance"]
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(
                            f"{assistance['level']} / {assistance['hint_count']} hint(s)"
                        ),
                    )
                )
                + " |"
            )
    else:
        lines.append("No supported assessment performance was recorded.")

    lines.extend(["", "## Prediction Error and Model Revision", ""])
    if predictions:
        for event in predictions:
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {_outcome(event)} prediction"
            )
    else:
        lines.append("Prediction error was not measured in this session.")
    if revisions:
        for event in revisions:
            lines.append(
                f"- **{markdown_text(event['decision'])}:** {markdown_text(event['model'])}"
                f" — {markdown_text(event['rationale'])}"
            )
    else:
        lines.append("No model revision was recorded.")

    lines.extend(["", "## Delayed Retrieval", ""])
    if retrievals:
        for event in retrievals:
            retrieval = event["retrieval"]
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {_outcome(event)} after "
                f"{markdown_text(retrieval['observed_delay_days'])} day(s)"
                f"{_retrieval_marker(event['evidence_mode'])}"
                f" (scheduled {markdown_text(retrieval['scheduled_date'])})."
            )
    else:
        lines.append("Delayed retrieval was not due or not measured in this session.")

    lines.extend(["", "## Calibration", ""])
    if calibrated:
        for event in calibrated:
            normalized = float(event["score"]) / float(event["max_score"])
            gap = float(event["confidence_before"]) - normalized
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** confidence "
                f"{event['confidence_before']:.3f}, normalized score {normalized:.3f}, "
                f"gap {gap:.3f}."
            )
    else:
        lines.append("Calibration was not measured before an answer in this session.")

    lines.extend(["", "## Course Grounding", ""])
    grounding_events = [*session_events, completion]
    references: list[tuple[str, str]] = []
    seen_references: set[tuple[str, str]] = set()
    for event in grounding_events:
        grounding = event.get("grounding")
        if grounding is None:
            continue
        for assertion_id in grounding["assertion_ids"]:
            authority_id = grounding.get("decision_event_id") or grounding.get("approval_event_id")
            key = (authority_id, assertion_id)
            if key not in seen_references:
                seen_references.add(key)
                references.append(key)
    if references:
        current_approval_id: str | None = None
        for approval_id, assertion_id in references:
            view = timeline.approval_views[approval_id]
            if approval_id != current_approval_id:
                approval = view["approval"]
                source = view["source"]
                lines.extend(
                    [
                        f"### Decision/Approval `{markdown_text(approval_id)}`",
                        "",
                        f"- **Source version:** `{markdown_text(source['source_version_id'])}`",
                        f"- **Source SHA-256:** `{source['sha256']}`",
                        f"- **Decided:** {markdown_text(approval['occurred_at'])}",
                    ]
                )
                current_approval_id = approval_id
            assertion = timeline.resolve_assertion(approval_id, assertion_id)
            _render_assertion(lines, assertion)
    else:
        lines.append("No approved syllabus assertion was cited in this session.")

    lines.extend(
        [
            "",
            "## Next Action and Review",
            "",
            f"- **Next action:** {markdown_text(completion['next_action'])}",
            f"- **Next review:** "
            f"{markdown_text(completion['next_review_date'] or 'not scheduled')}",
        ]
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_all_receipts(
    profile: dict[str, Any],
    events: list[dict[str, Any]],
    timeline: GroundingTimeline | None = None,
) -> dict[str, bytes]:
    """Render every Session Receipt, keyed by its path under sessions/."""
    receipts: dict[str, bytes] = {}
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    for event in events:
        if event["kind"] == "session_completed":
            receipts[f"sessions/{event['session_id']}.md"] = render_receipt(
                profile, events, event, timeline
            )
    return receipts
