"""Deterministic Obsidian-readable dashboard and Session Receipt renderers."""

from __future__ import annotations

import html
from typing import Any

GENERATED_WARNING = (
    "> [!warning] Generated by Dunk. Do not edit this file; edit `profile.yaml` instead.\n"
)


def markdown_text(value: Any) -> str:
    """Escape untrusted text for table cells and block marker safety."""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = html.escape(text, quote=False).replace("|", "\\|").replace("\n", "<br>")
    return text


def _outcome(event: dict[str, Any]) -> str:
    result = event["outcome"]
    if "score" in event:
        result += f" ({event['score']}/{event['max_score']})"
    return markdown_text(result)


def render_dashboard(state: dict[str, Any]) -> bytes:
    lines = [
        "# Dunk Learning Dashboard",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(state['domain'])}",
        f"- **Goal:** {markdown_text(state['goal'])}",
        f"- **Stage:** `{markdown_text(state['stage'])}`",
        f"- **Revision:** {state['revision']}",
        f"- **Generation:** {state['generation']}",
        f"- **Next review:** {markdown_text(state['next_review_date'] or 'not scheduled')}",
        "",
        "## Evidence",
        "",
        "| Subject | Status | Latest independent | Latest supported | Retrieval | Transfer |",
        "|---|---|---|---|---|---|",
    ]
    if state["subjects"]:
        for subject in state["subjects"]:
            independent = subject["independent"]
            supported = subject["supported"]
            independent_text = (
                f"{independent['outcome']} / {independent['operation']}"
                if independent
                else "not measured"
            )
            supported_text = (
                f"{supported['outcome']} / {supported['operation']}" if supported else "none"
            )
            retrieval = subject["retrieval"]
            if retrieval["status"] == "measured":
                retrieval_text = (
                    f"{retrieval['latest']['outcome']} after "
                    f"{retrieval['latest']['delay_days']} day(s)"
                )
            else:
                retrieval_text = "not measured"
            transfer = subject["transfer"]
            transfer_text = (
                f"{transfer['count']} novel task(s)" if transfer["count"] else "not measured"
            )
            lines.append(
                "| "
                + " | ".join(
                    markdown_text(value)
                    for value in (
                        subject["label"],
                        subject["status"],
                        independent_text,
                        supported_text,
                        retrieval_text,
                        transfer_text,
                    )
                )
                + " |"
            )
    else:
        lines.append(
            "| _No structured assessment evidence yet_ | insufficient-evidence | — | — | — | — |"
        )

    calibration = state["calibration"]
    lines.extend(["", "## Calibration", ""])
    if calibration["status"] == "measured":
        lines.extend(
            [
                f"- Paired predictions: {calibration['count']}",
                f"- Mean confidence: {calibration['mean_confidence']:.3f}",
                f"- Mean normalized score: {calibration['mean_normalized_score']:.3f}",
                f"- Mean confidence minus score: {calibration['mean_gap']:.3f}",
            ]
        )
    else:
        lines.append(
            "Calibration not measured (requires confidence recorded before a scored outcome)."
        )

    lines.extend(["", "## Current Model", ""])
    if state["current_model"]:
        model = state["current_model"]
        lines.extend(
            [
                f"- **Decision:** `{markdown_text(model['decision'])}`",
                f"- **Model:** {markdown_text(model['model'])}",
                f"- **Revision rationale:** {markdown_text(model['rationale'])}",
            ]
        )
    else:
        lines.append("No structured model revision recorded.")

    lines.extend(["", "## Completed Sessions", ""])
    if state["completed_sessions"]:
        for session in state["completed_sessions"]:
            lines.append(
                f"- [[{markdown_text(session['receipt'])}|{markdown_text(session['session_id'])}]]"
                f" — {markdown_text(session['completed_at'])}"
            )
    else:
        lines.append("No completed sessions yet.")

    lines.extend(["", "## Imported Legacy Claims", ""])
    if state["legacy_imports"]:
        lines.append(
            "Legacy claims are unverified prior context only and are never counted as evidence, mastery, retrieval, or calibration."
        )
        for item in state["legacy_imports"]:
            claims = item["claims"]
            counts = ", ".join(
                f"{key}: {len(value)}"
                for key, value in sorted(claims.items())
                if isinstance(value, list)
            )
            lines.append(
                f"- `{item['source_sha256'][:12]}` — {markdown_text(counts or 'snapshot imported')}"
            )
    else:
        lines.append("No legacy snapshot imported.")

    if state["next_action"]:
        lines.extend(["", "## Next Action", "", markdown_text(state["next_action"])])
    return ("\n".join(lines) + "\n").encode("utf-8")


def _session_events(
    events: list[dict[str, Any]], completion: dict[str, Any]
) -> list[dict[str, Any]]:
    wanted = set(completion["evidence_event_ids"])
    return [event for event in events if event["event_id"] in wanted]


def render_receipt(
    profile: dict[str, Any],
    events: list[dict[str, Any]],
    completion: dict[str, Any],
) -> bytes:
    session_events = _session_events(events, completion)
    independent = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "independent"
    ]
    supported = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "supported"
    ]
    predictions = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["operation"] == "predict"
    ]
    revisions = [event for event in session_events if event["kind"] == "model_revision"]
    retrievals = [
        event
        for event in session_events
        if event["kind"] == "assessment"
        and event.get("retrieval", {}).get("observed_delay_days", 0) > 0
    ]
    calibrated = [event for event in session_events if "confidence_before" in event]

    lines = [
        f"# Session Receipt — {markdown_text(completion['session_id'])}",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(profile['domain'])}",
        f"- **Completed:** {markdown_text(completion['occurred_at'])}",
        "",
        "## Independent Evidence",
        "",
    ]
    if independent:
        lines.extend(["| Subject | Operation | Outcome | Novelty |", "|---|---|---|---|"])
        for event in independent:
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(event["novelty"]),
                    )
                )
                + " |"
            )
    else:
        lines.append("No independent assessment evidence was recorded in this session.")

    lines.extend(["", "## Supported Performance", ""])
    if supported:
        lines.extend(["| Subject | Operation | Outcome | Assistance |", "|---|---|---|---|"])
        for event in supported:
            assistance = event["assistance"]
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(
                            f"{assistance['level']} / {assistance['hint_count']} hint(s)"
                        ),
                    )
                )
                + " |"
            )
    else:
        lines.append("No supported assessment performance was recorded.")

    lines.extend(["", "## Prediction Error and Model Revision", ""])
    if predictions:
        for event in predictions:
            error = (
                "no recorded error"
                if event["outcome"] == "pass"
                else f"{event['outcome']} prediction"
            )
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {markdown_text(error)}"
            )
    else:
        lines.append("Prediction error was not measured in this session.")
    if revisions:
        for event in revisions:
            lines.append(
                f"- **{markdown_text(event['decision'])}:** {markdown_text(event['model'])}"
                f" — {markdown_text(event['rationale'])}"
            )
    else:
        lines.append("No model revision was recorded.")

    lines.extend(["", "## Delayed Retrieval", ""])
    if retrievals:
        for event in retrievals:
            retrieval = event["retrieval"]
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {_outcome(event)} after "
                f"{markdown_text(retrieval['observed_delay_days'])} day(s)"
                f" (scheduled {markdown_text(retrieval['scheduled_date'])})."
            )
    else:
        lines.append("Delayed retrieval was not due or not measured in this session.")

    lines.extend(["", "## Calibration", ""])
    if calibrated:
        for event in calibrated:
            normalized = float(event["score"]) / float(event["max_score"])
            gap = float(event["confidence_before"]) - normalized
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** confidence "
                f"{event['confidence_before']:.3f}, normalized score {normalized:.3f}, gap {gap:.3f}."
            )
    else:
        lines.append("Calibration was not measured before an answer in this session.")

    lines.extend(
        [
            "",
            "## Next Action and Review",
            "",
            f"- **Next action:** {markdown_text(completion['next_action'])}",
            f"- **Next review:** {markdown_text(completion['next_review_date'] or 'not scheduled')}",
        ]
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_all_receipts(profile: dict[str, Any], events: list[dict[str, Any]]) -> dict[str, bytes]:
    receipts: dict[str, bytes] = {}
    for event in events:
        if event["kind"] == "session_completed":
            receipts[f"sessions/{event['session_id']}.md"] = render_receipt(profile, events, event)
    return receipts
