"""Deterministic Obsidian-readable dashboard and Session Receipt renderers."""

from __future__ import annotations

import html
import json
import re
from typing import Any

from .grounding import GroundingTimeline, reduce_grounding_timeline

GENERATED_WARNING = (
    "> [!warning] Generated by Dunk. Do not edit this file; edit `profile.yaml` instead.\n"
)
SYLLABUS_GENERATED_WARNING = (
    "> [!warning] Generated from canonical `profile.yaml` and `events.jsonl`. "
    "Use the Dunk store commands instead of editing this receipt.\n"
)


def markdown_text(value: Any) -> str:
    """Escape untrusted inline Markdown, table cells, and block marker syntax."""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = html.escape(text, quote=False).replace("\\", "\\\\").replace("|", "\\|")
    for marker in ("`", "*", "[", "]"):
        text = text.replace(marker, f"\\{marker}")
    return text.replace("\n", "<br>")


def _outcome(event: dict[str, Any]) -> str:
    result = event["outcome"]
    if "score" in event:
        result += f" ({event['score']}/{event['max_score']})"
    return markdown_text(result)


def _retrieval_marker(evidence_mode: str) -> str:
    return "" if evidence_mode == "independent" else " (supported)"


def _normalized_text(value: Any) -> str:
    if isinstance(value, str):
        return markdown_text(value)
    return markdown_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    )


def _page_text_fence(text: str) -> str:
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    return "`" * max(4, longest + 1)


def _citation_text(citation: dict[str, Any]) -> str:
    return (
        f"page {citation['page_number']}, chars {citation['start_char']}–{citation['end_char']}: "
        f"“{markdown_text(citation['quote'])}”"
    )


def _render_assertion(lines: list[str], assertion: dict[str, Any]) -> None:
    normalized = _normalized_text(assertion["normalized_value"])
    lines.append(
        f"- `{markdown_text(assertion['assertion_id'])}` — "
        f"`{markdown_text(assertion['field'])}` = {normalized} "
        f"(`{markdown_text(assertion['status'])}`)"
    )
    if assertion.get("origin") == "learner_correction":
        lines.append(
            f"  - Learner correction of `{markdown_text(assertion['source_assertion_id'])}`; "
            f"document value: {_normalized_text(assertion['document_value'])}; "
            f"rationale: {markdown_text(assertion['rationale'])}"
        )
    for citation in assertion["citations"]:
        lines.append(f"  - {_citation_text(citation)}")
    note = assertion.get("note") or assertion.get("document_note")
    if note:
        lines.append(f"  - Note: {markdown_text(note)}")


def _source_assertion_view(assertion: dict[str, Any]) -> dict[str, Any]:
    result = {
        "assertion_id": assertion["assertion_id"],
        "citations": assertion["evidence"],
        "field": assertion["field"],
        "normalized_value": assertion["normalized_value"],
        "origin": "document",
        "source_assertion_id": assertion["assertion_id"],
        "status": assertion["status"],
    }
    if "note" in assertion:
        result["note"] = assertion["note"]
    return result


SYLLABUS_SECTION_PREFIXES = (
    ("Course & Offering", ("course.", "offering.")),
    ("Staff & Logistics", ("staff.", "class.", "tutorial.")),
    ("References", ("reference.",)),
    ("Assessment", ("assessment.", "milestone.")),
    ("Policies", ("policy.",)),
    ("Coverage & Schedule", ("coverage.", "schedule.")),
)


def render_syllabus_receipt(timeline: GroundingTimeline, source_event: dict[str, Any]) -> bytes:
    """Render one digest-bound source version and its immutable approval history."""
    source = source_event["source"]
    approvals = [
        approval
        for approval in timeline.approvals_by_id.values()
        if approval["source_version_id"] == source["source_version_id"]
    ]
    latest_view = timeline.approval_views[approvals[-1]["event_id"]] if approvals else None
    current_view = timeline.current_view()
    is_active = bool(
        current_view
        and current_view["source"]["source"]["source_version_id"]
        == source["source_version_id"]
    )
    if not approvals:
        status = "Approval Required"
    elif is_active:
        status = "Approved"
    else:
        status = "Historically Approved — Superseded"
    extractor = source_event["extraction"]
    lines = [
        f"# Syllabus Intake Receipt — {status}",
        "",
        SYLLABUS_GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Source version:** `{markdown_text(source['source_version_id'])}`",
        f"- **Source ID:** `{markdown_text(source['source_id'])}`",
        f"- **Filename:** {markdown_text(source['original_filename'])}",
        f"- **SHA-256:** `{source['sha256']}`",
        f"- **Bytes/pages:** {source['byte_size']} bytes / {source['page_count']} page(s)",
        f"- **Ingested:** {markdown_text(source_event['occurred_at'])}",
        f"- **Retention:** `{markdown_text(source['content_retention'])}`; "
        "original PDF bytes are not stored",
        f"- **Extraction:** `{markdown_text(extractor['extractor_name'])}` "
        f"`{markdown_text(extractor['extractor_version'])}` via "
        f"`{markdown_text(extractor['method'])}`",
        f"- **Assertion set:** `{source_event['assertion_set_sha256']}`",
    ]
    if approvals and not is_active and current_view:
        current_approval = current_view["approval"]
        current_source = current_view["source"]["source"]
        lines.extend(
            [
                f"- **Superseded by approval:** `{markdown_text(current_approval['event_id'])}`",
                f"- **Current source version:** "
                f"`{markdown_text(current_source['source_version_id'])}`",
            ]
        )

    if latest_view:
        rendered_assertions = latest_view["effective_assertions"]
    else:
        rendered_assertions = [
            _source_assertion_view(assertion)
            for assertion in source_event["assertions"]
            if assertion["status"] == "specified"
        ]

    for heading, prefixes in SYLLABUS_SECTION_PREFIXES:
        lines.extend(["", f"## {heading}", ""])
        section = [
            assertion
            for assertion in rendered_assertions
            if assertion["status"] == "specified" and assertion["field"].startswith(prefixes)
        ]
        if section:
            for assertion in section:
                _render_assertion(lines, assertion)
        else:
            lines.append("No settled assertion in this section.")

    if latest_view:
        unresolved = [
            assertion
            for assertion in latest_view["effective_assertions"]
            if assertion["status"] != "specified"
        ] + latest_view["unresolved_assertions"]
        source_order = {
            assertion["assertion_id"]: index
            for index, assertion in enumerate(source_event["assertions"])
        }
        unresolved.sort(key=lambda assertion: source_order[assertion["source_assertion_id"]])
    else:
        unresolved = [
            _source_assertion_view(assertion)
            for assertion in source_event["assertions"]
            if assertion["status"] != "specified"
        ]
    lines.extend(["", "## Unresolved / Not Specified", ""])
    if unresolved:
        for assertion in unresolved:
            _render_assertion(lines, assertion)
            if "disposition" in assertion:
                lines.append(f"  - Disposition: `{markdown_text(assertion['disposition'])}`")
    else:
        lines.append("No unresolved, deferred, or not-specified assertions.")

    lines.extend(["", "## Approval History", ""])
    if approvals:
        for approval in approvals:
            accepted = ", ".join(
                f"`{markdown_text(item)}`" for item in approval["accepted_assertion_ids"]
            )
            deferred = ", ".join(
                f"`{markdown_text(item)}`" for item in approval["deferred_assertion_ids"]
            )
            lines.extend(
                [
                    f"### `{markdown_text(approval['event_id'])}`",
                    "",
                    f"- **Occurred:** {markdown_text(approval['occurred_at'])}",
                    f"- **Actor:** `{markdown_text(approval['actor']['type'])}:"
                    f"{markdown_text(approval['actor']['id'])}`",
                    f"- **Approval set:** `{approval['approval_set_sha256']}`",
                    f"- **Supersedes:** "
                    f"`{markdown_text(approval['supersedes_approval_event_id'] or 'none')}`",
                    f"- **Accepted:** {accepted or 'none'}",
                    f"- **Deferred:** {deferred or 'none'}",
                ]
            )
            if approval["corrections"]:
                lines.append("- **Corrections:**")
                source_by_id = {
                    assertion["assertion_id"]: assertion for assertion in source_event["assertions"]
                }
                for correction in approval["corrections"]:
                    target = source_by_id[correction["target_assertion_id"]]
                    lines.append(
                        f"  - `{markdown_text(correction['correction_assertion_id'])}` replaces "
                        f"`{markdown_text(target['assertion_id'])}` value "
                        f"{_normalized_text(target['normalized_value'])} with "
                        f"{_normalized_text(correction['normalized_value'])}; "
                        f"{markdown_text(correction['rationale'])}"
                    )
                    for citation in target["evidence"]:
                        lines.append(
                            f"    - Preserved document citation: {_citation_text(citation)}"
                        )
            else:
                lines.append("- **Corrections:** none")
            lines.append("")
    else:
        lines.append("No approval has been recorded for this source version.")

    lines.extend(["", "## Canonical Page Text", ""])
    for page in source_event["pages"]:
        fence = _page_text_fence(page["text"])
        lines.extend(
            [
                f"### Page {page['page_number']}",
                "",
                f"{fence}text",
                page["text"],
                fence,
                "",
            ]
        )
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def render_all_syllabus_receipts(
    events: list[dict[str, Any]], timeline: GroundingTimeline | None = None
) -> dict[str, bytes]:
    """Render every source-version receipt after validating the shared timeline."""
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    return {
        f"syllabus/{version_id}.md": render_syllabus_receipt(
            timeline, timeline.sources_by_version[version_id]
        )
        for version_id in timeline.source_order
    }


def _dashboard_grounding_lines(grounding: dict[str, Any]) -> list[str]:
    lines = ["", "## Course Grounding", ""]
    status = grounding["status"]
    lines.append(f"- **Status:** `{markdown_text(status)}`")
    active = grounding["active_source"]
    if active is None:
        if status == "ungrounded":
            lines.append(
                "- **Source:** unknown; legacy planning topics are ungrounded and non-citable"
            )
        else:
            lines.append("- **Source:** no approved source is active")
    else:
        approval = grounding["active_approval"]
        lines.extend(
            [
                f"- **Active source:** {markdown_text(active['filename'])}",
                f"- **Version:** `{markdown_text(active['source_version_id'])}`",
                f"- **SHA-256:** `{active['sha256']}`",
                f"- **Approval:** `{markdown_text(approval['event_id'])}`",
                f"- **Unresolved/deferred:** {len(grounding['unresolved_assertions'])}",
                f"- **Receipt:** [[{markdown_text(active['receipt'])}|Syllabus Intake Receipt]]",
            ]
        )
    if grounding["pending_sources"]:
        label = "Pending update" if active else "Approval required"
        for pending in grounding["pending_sources"]:
            lines.append(
                f"- **{label}:** {markdown_text(pending['filename'])} "
                f"(`{markdown_text(pending['source_version_id'])}`) — "
                f"[[{markdown_text(pending['receipt'])}|review intake receipt]]"
            )
    return lines


def render_dashboard(state: dict[str, Any]) -> bytes:
    """Render the domain dashboard as Obsidian-readable Markdown."""
    lines = [
        "# Dunk Learning Dashboard",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(state['domain'])}",
        f"- **Goal:** {markdown_text(state['goal'])}",
        f"- **Stage:** `{markdown_text(state['stage'])}`",
        f"- **Revision:** {state['revision']}",
        f"- **Generation:** {state['generation']}",
        f"- **Next review:** {markdown_text(state['next_review_date'] or 'not scheduled')}",
    ]
    lines.extend(_dashboard_grounding_lines(state["grounding"]))
    lines.extend(
        [
            "",
            "## Evidence",
            "",
            "| Subject | Status | Latest independent | Latest supported | Retrieval | Transfer |",
            "|---|---|---|---|---|---|",
        ]
    )
    if state["subjects"]:
        for subject in state["subjects"]:
            independent = subject["independent"]
            supported = subject["supported"]
            independent_text = (
                f"{independent['outcome']} / {independent['operation']}"
                if independent
                else "not measured"
            )
            supported_text = (
                f"{supported['outcome']} / {supported['operation']}" if supported else "none"
            )
            retrieval = subject["retrieval"]
            if retrieval["status"] == "measured":
                latest_retrieval = retrieval["latest"]
                retrieval_text = (
                    f"{latest_retrieval['outcome']} after {latest_retrieval['delay_days']} day(s)"
                    f"{_retrieval_marker(latest_retrieval['evidence_mode'])}"
                )
            else:
                retrieval_text = "not measured"
            transfer = subject["transfer"]
            transfer_text = (
                f"{transfer['count']} novel task(s)" if transfer["count"] else "not measured"
            )
            lines.append(
                "| "
                + " | ".join(
                    markdown_text(value)
                    for value in (
                        subject["label"],
                        subject["status"],
                        independent_text,
                        supported_text,
                        retrieval_text,
                        transfer_text,
                    )
                )
                + " |"
            )
    else:
        lines.append(
            "| _No structured assessment evidence yet_ | insufficient-evidence | — | — | — | — |"
        )

    calibration = state["calibration"]
    lines.extend(["", "## Calibration", ""])
    if calibration["status"] == "measured":
        lines.extend(
            [
                f"- Paired predictions: {calibration['count']}",
                f"- Mean confidence: {calibration['mean_confidence']:.3f}",
                f"- Mean normalized score: {calibration['mean_normalized_score']:.3f}",
                f"- Mean confidence minus score: {calibration['mean_gap']:.3f}",
            ]
        )
    else:
        lines.append(
            "Calibration not measured (requires confidence recorded before a scored outcome)."
        )

    lines.extend(["", "## Current Model", ""])
    if state["current_model"]:
        model = state["current_model"]
        lines.extend(
            [
                f"- **Decision:** `{markdown_text(model['decision'])}`",
                f"- **Model:** {markdown_text(model['model'])}",
                f"- **Revision rationale:** {markdown_text(model['rationale'])}",
            ]
        )
    else:
        lines.append("No structured model revision recorded.")

    lines.extend(["", "## Completed Sessions", ""])
    if state["completed_sessions"]:
        for session in state["completed_sessions"]:
            lines.append(
                f"- [[{markdown_text(session['receipt'])}|{markdown_text(session['session_id'])}]]"
                f" — {markdown_text(session['completed_at'])}"
            )
    else:
        lines.append("No completed sessions yet.")

    lines.extend(["", "## Imported Legacy Claims", ""])
    if state["legacy_imports"]:
        lines.append(
            "Legacy claims are unverified prior context only and are never counted "
            "as evidence, mastery, retrieval, or calibration."
        )
        for item in state["legacy_imports"]:
            claims = item["claims"]
            counts = ", ".join(
                f"{key}: {len(value)}"
                for key, value in sorted(claims.items())
                if isinstance(value, list)
            )
            lines.append(
                f"- `{item['source_sha256'][:12]}` — {markdown_text(counts or 'snapshot imported')}"
            )
    else:
        lines.append("No legacy snapshot imported.")

    if state["next_action"]:
        lines.extend(["", "## Next Action", "", markdown_text(state["next_action"])])
    return ("\n".join(lines) + "\n").encode("utf-8")


def _session_events(
    events: list[dict[str, Any]], completion: dict[str, Any]
) -> list[dict[str, Any]]:
    wanted = set(completion["evidence_event_ids"])
    return [event for event in events if event["event_id"] in wanted]


def render_receipt(
    profile: dict[str, Any],
    events: list[dict[str, Any]],
    completion: dict[str, Any],
    timeline: GroundingTimeline | None = None,
) -> bytes:
    """Render one Session Receipt from a completion event and its cited evidence."""
    session_events = _session_events(events, completion)
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    independent = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "independent"
    ]
    supported = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["evidence_mode"] == "supported"
    ]
    predictions = [
        event
        for event in session_events
        if event["kind"] == "assessment" and event["operation"] == "predict"
    ]
    revisions = [event for event in session_events if event["kind"] == "model_revision"]
    retrievals = [
        event
        for event in session_events
        if event["kind"] == "assessment"
        and event.get("retrieval", {}).get("observed_delay_days", 0) > 0
    ]
    calibrated = [event for event in session_events if "confidence_before" in event]

    lines = [
        f"# Session Receipt — {markdown_text(completion['session_id'])}",
        "",
        GENERATED_WARNING.rstrip("\n"),
        "",
        f"- **Domain:** {markdown_text(profile['domain'])}",
        f"- **Completed:** {markdown_text(completion['occurred_at'])}",
        "",
        "## Independent Evidence",
        "",
    ]
    if independent:
        lines.extend(["| Subject | Operation | Outcome | Novelty |", "|---|---|---|---|"])
        for event in independent:
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(event["novelty"]),
                    )
                )
                + " |"
            )
    else:
        lines.append("No independent assessment evidence was recorded in this session.")

    lines.extend(["", "## Supported Performance", ""])
    if supported:
        lines.extend(["| Subject | Operation | Outcome | Assistance |", "|---|---|---|---|"])
        for event in supported:
            assistance = event["assistance"]
            lines.append(
                "| "
                + " | ".join(
                    (
                        markdown_text(event["subject"]["label"]),
                        markdown_text(event["operation"]),
                        _outcome(event),
                        markdown_text(
                            f"{assistance['level']} / {assistance['hint_count']} hint(s)"
                        ),
                    )
                )
                + " |"
            )
    else:
        lines.append("No supported assessment performance was recorded.")

    lines.extend(["", "## Prediction Error and Model Revision", ""])
    if predictions:
        for event in predictions:
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {_outcome(event)} prediction"
            )
    else:
        lines.append("Prediction error was not measured in this session.")
    if revisions:
        for event in revisions:
            lines.append(
                f"- **{markdown_text(event['decision'])}:** {markdown_text(event['model'])}"
                f" — {markdown_text(event['rationale'])}"
            )
    else:
        lines.append("No model revision was recorded.")

    lines.extend(["", "## Delayed Retrieval", ""])
    if retrievals:
        for event in retrievals:
            retrieval = event["retrieval"]
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** {_outcome(event)} after "
                f"{markdown_text(retrieval['observed_delay_days'])} day(s)"
                f"{_retrieval_marker(event['evidence_mode'])}"
                f" (scheduled {markdown_text(retrieval['scheduled_date'])})."
            )
    else:
        lines.append("Delayed retrieval was not due or not measured in this session.")

    lines.extend(["", "## Calibration", ""])
    if calibrated:
        for event in calibrated:
            normalized = float(event["score"]) / float(event["max_score"])
            gap = float(event["confidence_before"]) - normalized
            lines.append(
                f"- **{markdown_text(event['subject']['label'])}:** confidence "
                f"{event['confidence_before']:.3f}, normalized score {normalized:.3f}, "
                f"gap {gap:.3f}."
            )
    else:
        lines.append("Calibration was not measured before an answer in this session.")

    lines.extend(["", "## Course Grounding", ""])
    grounding_events = [*session_events, completion]
    references: list[tuple[str, str]] = []
    seen_references: set[tuple[str, str]] = set()
    for event in grounding_events:
        grounding = event.get("grounding")
        if grounding is None:
            continue
        for assertion_id in grounding["assertion_ids"]:
            key = (grounding["approval_event_id"], assertion_id)
            if key not in seen_references:
                seen_references.add(key)
                references.append(key)
    if references:
        current_approval_id: str | None = None
        for approval_id, assertion_id in references:
            view = timeline.approval_views[approval_id]
            if approval_id != current_approval_id:
                approval = view["approval"]
                source = view["source"]["source"]
                lines.extend(
                    [
                        f"### Approval `{markdown_text(approval_id)}`",
                        "",
                        f"- **Source version:** `{markdown_text(source['source_version_id'])}`",
                        f"- **Source SHA-256:** `{source['sha256']}`",
                        f"- **Approved:** {markdown_text(approval['occurred_at'])}",
                    ]
                )
                current_approval_id = approval_id
            assertion = timeline.resolve_assertion(approval_id, assertion_id)
            _render_assertion(lines, assertion)
    else:
        lines.append("No approved syllabus assertion was cited in this session.")

    lines.extend(
        [
            "",
            "## Next Action and Review",
            "",
            f"- **Next action:** {markdown_text(completion['next_action'])}",
            f"- **Next review:** "
            f"{markdown_text(completion['next_review_date'] or 'not scheduled')}",
        ]
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_all_receipts(
    profile: dict[str, Any],
    events: list[dict[str, Any]],
    timeline: GroundingTimeline | None = None,
) -> dict[str, bytes]:
    """Render every Session Receipt, keyed by its path under sessions/."""
    receipts: dict[str, bytes] = {}
    if timeline is None:
        timeline = reduce_grounding_timeline(events)
    for event in events:
        if event["kind"] == "session_completed":
            receipts[f"sessions/{event['session_id']}.md"] = render_receipt(
                profile, events, event, timeline
            )
    return receipts
