#!/usr/bin/env bash
# Ralph Loop — Autonomous coding loop with per-task context assembly
# Generated by /ralph start. Safe to edit.

set -euo pipefail

RALPH_DIR="docs/ralph"
SPEC_FILE="$RALPH_DIR/SPEC.md"
PLAN_FILE="$RALPH_DIR/PLAN.md"
TASKS_DIR="$RALPH_DIR/tasks"
LOG_DIR="$RALPH_DIR/logs"
PROTOCOL_FILE="$RALPH_DIR/iteration-protocol.md"
MAX_ITERATIONS="${MAX_ITERATIONS:-25}"
ITERATION=0
LAST_TASK=""

mkdir -p "$LOG_DIR"

# --- Helper: extract a ## section from SPEC.md by heading name ---
extract_section() {
    local file="$1"
    local section="$2"
    awk -v section="$section" '
        BEGIN { found=0 }
        /^## / {
            if (found) exit
            gsub(/^## */, "")
            if ($0 == section) found=1
        }
        found { print }
    ' "$file"
}

# --- Helper: parse YAML frontmatter array field ---
parse_frontmatter_array() {
    local file="$1"
    local field="$2"
    sed -n '/^---$/,/^---$/p' "$file" \
        | grep "^${field}:" \
        | sed "s/^${field}: *\[//; s/\] *$//; s/, */\n/g"
}

# --- Helper: strip YAML frontmatter from a file ---
strip_frontmatter() {
    local file="$1"
    awk 'BEGIN{n=0} /^---$/{n++; if(n==2){getline; found=1}} found{print}' "$file"
}

# --- Helper: block a task without relying on platform-specific sed -i ---
mark_task_blocked() {
    local task="$1"
    local reason="$2"
    local temporary="${PLAN_FILE}.tmp.$$"

    awk -v task="$task" -v reason="$reason" '
        $1 == "-" && $2 == "[" && $3 == "]" && $4 == task {
            remainder = $0
            sub(/^- \[ \] [0-9][0-9]*/, "", remainder)
            print "- [BLOCKED: " reason "] " task remainder
            next
        }
        { print }
    ' "$PLAN_FILE" > "$temporary"
    mv "$temporary" "$PLAN_FILE"
}

# --- Preflight checks ---
for f in "$SPEC_FILE" "$PLAN_FILE" "$PROTOCOL_FILE"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Missing required file: $f"
        echo "Run the ralph planning skill first to generate artifacts."
        exit 1
    fi
done

if [[ ! "$MAX_ITERATIONS" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: MAX_ITERATIONS must be a positive integer." >&2
    exit 1
fi

TASK_FILES=("$TASKS_DIR"/*.md)
if [[ ! -d "$TASKS_DIR" ]] || [[ ! -f "${TASK_FILES[0]}" ]]; then
    echo "ERROR: No task files found in $TASKS_DIR"
    exit 1
fi

echo "=== Ralph Loop Starting ==="
echo "Spec: $SPEC_FILE"
echo "Plan: $PLAN_FILE"
echo "Tasks: ${#TASK_FILES[@]} task files"
echo "Max iterations: $MAX_ITERATIONS"
echo ""

# --- Main loop ---
while :; do
    # Find the leading task number from the next unchecked plan item.
    NEXT=$(sed -n 's/^- \[ \] \([0-9][0-9]*\).*/\1/p' "$PLAN_FILE" | head -1) || true

    if [[ -z "$NEXT" ]]; then
        echo ""
        echo "=== Ralph Loop Complete ==="
        echo "All tasks are complete or blocked."
        echo "Check $PLAN_FILE for final status."
        break
    fi

    if [[ "$NEXT" == "$LAST_TASK" ]]; then
        echo "WARNING: Task $NEXT remained unchecked after its iteration. Marking it blocked." >&2
        mark_task_blocked "$NEXT" "repeated without completion"
        LAST_TASK=""
        continue
    fi

    if (( ITERATION >= MAX_ITERATIONS )); then
        echo "ERROR: Reached MAX_ITERATIONS=$MAX_ITERATIONS with unchecked tasks remaining." >&2
        exit 1
    fi

    ITERATION=$((ITERATION + 1))

    # Find the task file matching this number.
    TASK_FILE=""
    for candidate in "$TASKS_DIR/${NEXT}-"*.md; do
        if [[ -f "$candidate" ]]; then
            TASK_FILE="$candidate"
            break
        fi
    done

    if [[ -z "$TASK_FILE" ]]; then
        echo "WARNING: No task file found for task $NEXT. Skipping."
        mark_task_blocked "$NEXT" "task file missing"
        LAST_TASK=""
        continue
    fi

    echo "--- Iteration $ITERATION: Task $NEXT ($(basename "$TASK_FILE")) ---"

    # Parse frontmatter declarations.
    SECTIONS=$(parse_frontmatter_array "$TASK_FILE" "spec-sections") || true
    CODEBASE_FILES=$(parse_frontmatter_array "$TASK_FILE" "codebase-files") || true

    # Assemble the prompt dynamically with real newline characters.
    PROMPT=""

    # 1. Inject declared spec sections
    if [[ -n "$SECTIONS" ]]; then
        PROMPT+="# Project Spec (relevant sections)"$'\n\n'
        while IFS= read -r section; do
            section=$(printf '%s' "$section" | xargs)
            [[ -z "$section" ]] && continue
            EXTRACTED=$(extract_section "$SPEC_FILE" "$section")
            if [[ -n "$EXTRACTED" ]]; then
                PROMPT+="$EXTRACTED"
                PROMPT+=$'\n\n'
            else
                PROMPT+="## $section"$'\n'"[Section not found in spec]"$'\n\n'
            fi
        done <<< "$SECTIONS"
    fi

    # 2. Inject declared codebase files
    if [[ -n "$CODEBASE_FILES" ]]; then
        PROMPT+="# Codebase Files (current state)"$'\n\n'
        while IFS= read -r filepath; do
            filepath=$(printf '%s' "$filepath" | xargs)
            [[ -z "$filepath" ]] && continue
            if [[ -f "$filepath" ]]; then
                PROMPT+="## File: $filepath"$'\n\n'
                PROMPT+='```'$'\n'
                PROMPT+="$(cat "$filepath")"
                PROMPT+=$'\n'
                PROMPT+='```'$'\n\n'
            else
                PROMPT+="## File: $filepath"$'\n'"[File not found — may not be created yet]"$'\n\n'
            fi
        done <<< "$CODEBASE_FILES"
    fi

    # 3. Inject task details (without frontmatter)
    PROMPT+="# Your Task"$'\n\n'
    PROMPT+="$(strip_frontmatter "$TASK_FILE")"
    PROMPT+=$'\n\n'

    # 4. Inject iteration protocol
    PROMPT+="$(cat "$PROTOCOL_FILE")"

    # Run Claude with the assembled prompt and preserve its exit status through tee.
    LAST_TASK="$NEXT"
    LOG_FILE="$LOG_DIR/iteration-$(printf '%02d' "$ITERATION").log"
    set +e
    printf '%s' "$PROMPT" | claude -p 2>&1 | tee "$LOG_FILE"
    PIPE_STATUSES=("${PIPESTATUS[@]}")
    set -e

    CLAUDE_STATUS="${PIPE_STATUSES[1]}"
    TEE_STATUS="${PIPE_STATUSES[2]}"
    if (( CLAUDE_STATUS != 0 )); then
        echo "ERROR: claude -p failed for task $NEXT with exit $CLAUDE_STATUS." >&2
        exit "$CLAUDE_STATUS"
    fi
    if (( TEE_STATUS != 0 )); then
        echo "ERROR: Failed to write iteration log for task $NEXT (tee exit $TEE_STATUS)." >&2
        exit "$TEE_STATUS"
    fi

    echo ""
    echo "--- Iteration $ITERATION complete ---"
    echo ""
done

echo ""
echo "Logs: $LOG_DIR/"
echo "Plan: $PLAN_FILE"
